name: yellowcab_ridge
dependencies:
  - jupyterlab=4.3.1
  - pip=24.3.1
  - python=3.12
  - ipywidgets=8.1.5
  - numpy=2.1.3
  - matplotlib=3.9.2
  - pandas=2.2.3
  - folium=0.18.0
  - geojson=3.1.0
  - nodejs=22.11.0

